import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { RecoilWrap } from './components/RecoilWrap/RecoilWrap';
import './styles/MainPlayer.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <title>Chakrulos</title>
                <meta name="description" content="Chakrulos" />
                <meta name="author" content="Chakrulos.ge" />
                <meta property="og:image" content="/favicon.ico" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body className={inter.className}>
                <RecoilWrap>{children}</RecoilWrap>
            </body>
        </html>
    );
}
