import { atom } from 'recoil';

export const sideBarOpenState = atom({
    key: 'sideBarOpen',
    default: false,
});

//albums placeholder
export const albumsState = atom({
    key: 'album',
    default: [
        {
            name: 'Niaz',
            lastName: 'Diasamidze',
            plays: '2019',
            nationality: 'Georgian',
            image: '/images/niaz.jpg',
            songs: [
                'Maia',
                'Grubeli,Qari,Niavi',
                'Siyvarulistvis',
                'Da Cxovreba Igi',
                'Dromale',
                'Galaqtioni',
                'Dro',
                'Ai Mtazeda',
                'Shota',
                'Qars',
                'Sipi',
                'Niavi Civis',
                'Siyvarulis Droa',
                'Ampelografia',
                'Nami Vels',
                'Gza',
                'Soxumi',
                'Qartveli',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Niaz',
            lastName: 'Diasamidze',
            plays: '2019',
            nationality: 'Georgian',
            image: '/images/niaz.jpg',
            songs: [
                'Maia',
                'Grubeli,Qari,Niavi',
                'Siyvarulistvis',
                'Da Cxovreba Igi',
                'Dromale',
                'Galaqtioni',
                'Dro',
                'Ai Mtazeda',
                'Shota',
                'Qars',
                'Sipi',
                'Niavi Civis',
                'Siyvarulis Droa',
                'Ampelografia',
                'Nami Vels',
                'Gza',
                'Soxumi',
                'Qartveli',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Niaz',
            lastName: 'Diasamidze',
            plays: '2019',
            nationality: 'Georgian',
            image: '/images/niaz.jpg',
            songs: [
                'Maia',
                'Grubeli,Qari,Niavi',
                'Siyvarulistvis',
                'Da Cxovreba Igi',
                'Dromale',
                'Galaqtioni',
                'Dro',
                'Ai Mtazeda',
                'Shota',
                'Qars',
                'Sipi',
                'Niavi Civis',
                'Siyvarulis Droa',
                'Ampelografia',
                'Nami Vels',
                'Gza',
                'Soxumi',
                'Qartveli',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Niaz',
            lastName: 'Diasamidze',
            plays: '2019',
            nationality: 'Georgian',
            image: '/images/niaz.jpg',
            songs: [
                'Maia',
                'Grubeli,Qari,Niavi',
                'Siyvarulistvis',
                'Da Cxovreba Igi',
                'Dromale',
                'Galaqtioni',
                'Dro',
                'Ai Mtazeda',
                'Shota',
                'Qars',
                'Sipi',
                'Niavi Civis',
                'Siyvarulis Droa',
                'Ampelografia',
                'Nami Vels',
                'Gza',
                'Soxumi',
                'Qartveli',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Niaz',
            lastName: 'Diasamidze',
            plays: '2019',
            nationality: 'Georgian',
            image: '/images/niaz.jpg',
            songs: [
                'Maia',
                'Grubeli,Qari,Niavi',
                'Siyvarulistvis',
                'Da Cxovreba Igi',
                'Dromale',
                'Galaqtioni',
                'Dro',
                'Ai Mtazeda',
                'Shota',
                'Qars',
                'Sipi',
                'Niavi Civis',
                'Siyvarulis Droa',
                'Ampelografia',
                'Nami Vels',
                'Gza',
                'Soxumi',
                'Qartveli',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Niaz',
            lastName: 'Diasamidze',
            plays: '2019',
            nationality: 'Georgian',
            image: '/images/niaz.jpg',
            songs: [
                'Maia',
                'Grubeli,Qari,Niavi',
                'Siyvarulistvis',
                'Da Cxovreba Igi',
                'Dromale',
                'Galaqtioni',
                'Dro',
                'Ai Mtazeda',
                'Shota',
                'Qars',
                'Sipi',
                'Niavi Civis',
                'Siyvarulis Droa',
                'Ampelografia',
                'Nami Vels',
                'Gza',
                'Soxumi',
                'Qartveli',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
    ],
});
