import { atom } from 'recoil';

export const sideBarOpenState = atom({
    key: 'sideBarOpen',
    default: false,
});

//albums placeholder
export const albumsState = atom({
    key: 'album',
    default: [
        {
            name: 'Niaz',
            lastName: 'Diasamidze',
            plays: '2019',
            nationality: 'Georgian',
            image: '/images/niaz.jpg',
            songs: [
                'Maia',
                'Grubeli,Qari,Niavi',
                'Siyvarulistvis',
                'Da Cxovreba Igi',
                'Dromale',
                'Galaqtioni',
                'Dro',
                'Ai Mtazeda',
                'Shota',
                'Qars',
                'Sipi',
                'Niavi Civis',
                'Siyvarulis Droa',
                'Ampelografia',
                'Nami Vels',
                'Gza',
                'Soxumi',
                'Qartveli',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Billie',
            lastName: 'Eilish',
            plays: '2019',
            nationality: 'American',
            image: '/images/Billie Eilish.png',
            songs: [
                '!BAD GUY',
                'Xanny',
                'all the good girls go to hell',
                'wish you were gay',
                'bury a friend',
                'bad guy',
                'listen before i go',
                'i love you',
                'you should see me in a crown',
                'bellyache',
                'ocean eyes',
                "when the party's over",
                'hospitality',
                'what do you want from me?',
                'ilomilo',
                'goodbye',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'IV-Dasi',
            lastName: 'IV-Dasi',
            plays: '2019',
            nationality: 'Georgian',
            image: '/images/iv-dasi.png',
            songs: ['Mamba', 'PARADISE', 'Qomagebi', 'Romantisto'],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Jansug',
            lastName: 'Kakhidze',
            plays: '2014',
            nationality: 'Georgian',
            image: '/images/image 6.png',
            songs: [
                'Maia',
                'Grubeli,Qari,Niavi',
                'Siyvarulistvis',
                'Da Cxovreba Igi',
                'Dromale',
                'Galaqtioni',
                'Dro',
                'Ai Mtazeda',
                'Shota',
                'Qars',
                'Sipi',
                'Niavi Civis',
                'Siyvarulis Droa',
                'Ampelografia',
                'Nami Vels',
                'Gza',
                'Soxumi',
                'Qartveli',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Travis',
            lastName: 'Scott',
            plays: '2019',
            nationality: 'South Korea',
            image: '/images/Billie Eilish.png',
            songs: [
                '!BAD GUY',
                'Xanny',
                'all the good girls go to hell',
                'wish you were gay',
                'bury a friend',
                'bad guy',
                'listen before i go',
                'i love you',
                'you should see me in a crown',
                'bellyache',
                'ocean eyes',
                "when the party's over",
                'hospitality',
                'what do you want from me?',
                'ilomilo',
                'goodbye',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
        {
            name: 'Imagine',
            lastName: 'Dragons',
            plays: '2019',
            nationality: 'South Korea',
            image: '/images/Billie Eilish.png',
            songs: [
                '!BAD GUY',
                'Xanny',
                'all the good girls go to hell',
                'wish you were gay',
                'bury a friend',
                'bad guy',
                'listen before i go',
                'i love you',
                'you should see me in a crown',
                'bellyache',
                'ocean eyes',
                "when the party's over",
                'hospitality',
                'what do you want from me?',
                'ilomilo',
                'goodbye',
            ],
            srcs: [
                '/mp3/Chakrulo - Chakhrulos.mp3',
                "/mp3/Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
                '/mp3/Gulsrad.mp3',
                '/mp3/Imagine Dragons - Believer (Official Music Video).mp3',
                '/mp3/Mukhambazi.mp3',
            ],
        },
    ],
});
